### ISSUE TITLE
Building project produces MEM file

### ISSUE THREAD

**Issue by jpryne** [timhutton/sdl-canvas-wasm#1]
I must be doing this wrong, but I followed the directions as best I could, (using emsdk on Win7,) yet produced a MEM file in place of the JS & WASM files. Any advice?

**Comment by timhutton** [comment]
Strange. I just tried it myself on Windows 10 using these instructions to install emscripten: http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html
(installing from git clone) and then with the exact instruction on our build page (emcc core.cpp -s WASM=1 -s USE_SDL=2 -O3 -o index.js) and it worked correctly. Are you doing the same thing?

**Comment by jpryne** [comment]
Yes, that's exactly what I did. There must be another factor. I'll try it again.

**Comment by jpryne** [comment]
Tried again, but this time adding "--memory-init-file 0" to the end of "emcc core.cpp -s WASM=1 -s USE_SDL=2 -O3 -o index.js" but got the same result. When I read [kripken's comment, "This is by design, .mem files are created in optimized builds to reduce size and improve startup speed,"](https://github.com/kripken/emscripten/issues/2537) I thought perhaps I'd changed some setting in order to get smaller file sizes. Will try re-installing emsdk next...

**Comment by jpryne** [comment]
![sdl-canvas2](https://user-images.githubusercontent.com/1497564/42287606-d3e23f8a-7f6b-11e8-8188-9dbf9a9d22db.png)

**Comment by timhutton** [comment]
Do you have anything unusual in your .emscripten file? (echo %EM_CONFIG% for its location.)  Mine is:

```
import os
LLVM_ROOT='F:/Tim/emsdk/clang/e1.37.36_64bit'
EMSCRIPTEN_NATIVE_OPTIMIZER='F:/Tim/emsdk/clang/e1.37.36_64bit/optimizer.exe'
BINARYEN_ROOT='F:/Tim/emsdk/clang/e1.37.36_64bit/binaryen'
NODE_JS='F:/Tim/emsdk/node/8.9.1_64bit/bin/node.exe'
PYTHON='F:/Tim/emsdk/python/2.7.13.1_64bit/python-2.7.13.amd64/python.exe'
JAVA='F:/Tim/emsdk/java/8.152_64bit/bin/java.exe'
EMSCRIPTEN_ROOT='F:/Tim/emsdk/emscripten/1.37.36'
SPIDERMONKEY_ENGINE = ''
V8_ENGINE = ''
TEMP_DIR = 'g:/temp'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

Are you on the master branch of emsdk, and have done a recent git pull? 


It does look like an install issue, see here: https://github.com/wasdk/wasdk/issues/2

**Comment by jpryne** [comment]
I installed emsdk from zip, & used (emsdk update). I will try cloning the repo instead. When I (echo %EM_CONFIG%) all I get is "%EM_CONFIG%" in response; no config?

**Comment by timhutton** [comment]
Installing from zip should work too, so good to know if it causes problems.

echo %EM_CONFIG% should show the current value of EM_CONFIG environment variable. It will only work after calling emsdk_env.bat which sets the environment variables for Emscripten.

**Comment by jpryne** [comment]
Ok, I cloned the emsdk repo & compiled from there, yet got the same result.

I ran emsdk_env.bat and set the environment variables, compiled again (from my original install) & got the same result. Heading out for the day, but will pick this up tonight...

**Comment by timhutton** [comment]
Suggestions:
1. Delete all your emscripten/binaryen and sdl-canvas-wasm installations, to avoid confusion.
2. Run exactly this sequence of commands and post the entire console output:
```
git clone https://github.com/juj/emsdk.git
cd emsdk
emsdk install latest
emsdk activate latest
emsdk_env
more %EM_CONFIG%
cd ..
git clone https://github.com/timhutton/sdl-canvas-wasm.git
cd sdl-canvas-wasm
dir
emcc core.cpp -s WASM=1 -s USE_SDL=2 -O3 -o index.js
dir
```

**Comment by jpryne** [comment]
This did the trick. Still unsure as to what was wrong before. Thanks & apologies for helping with a problem that clearly had nothing to do with your code.
[output.txt](https://github.com/timhutton/sdl-canvas-wasm/files/2167498/output.txt)

**Comment by timhutton** [comment]
Great, glad it worked.
